name: Active Engagement
favicon: null
layout_spectrum: 0.31288663926534355
typography_spectrum: 0.3037576279602945
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#222222'
    - '#b2b6b7'
    - '#990100'
    - '#555555'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
